title: zacheller@home:~/blog$
description: "Cybersecurity blog by a programming, pentesting, and pedagogy enthusiast."
author:
  name: "Zach Heller"
  email: "zach@zacheller.dev"
  url: "https://zacheller.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 4
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "zacheller"
year : "2022"
